name : welcome the User
on:
    push:
        branches:
            - master
jobs:
    welcome:
        runs-on: ubuntu-latest
          - name : "greet the user"
            run : echo "welcome"